# 开发 profile :连接aliyun数据库，用于开发连接用，对应禅道demo-aliyun
mysql:
  #    host: localhost
  #    port: 3306
  host: 10.180.245.169
  port: 3306
#  qinghengHost: 58.56.21.226
#  qinghengPort: 8835

spring:
  datasource:
    druid:
      name: default
      url: jdbc:mysql://${mysql.host}:${mysql.port}/us_inspur?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
      aop-patterns: com.wisdom.iwcs.service.*.*
  mvc:
    favicon:
      enabled: false
  aop:
    proxy-target-class: true
  rabbitmq:
    publisher-confirms: true #支持发布确认
    publisher-returns: true  #支持发布返回
    listener:
      simple:
        acknowledge-mode: manual #采用手动应答, 开启ACK
        concurrency: 1 #指定最小的消费者数量
        max-concurrency: 1 #指定最大的消费者数量


liquibase:
  contexts: dev
  enabled: true

server:
  port: 8088
  tomcat:
    maxHttpHeaderSize: 66665536
management:
  port: 54001

  health:
    redis:
      enabled: false
  security:
    enabled: false
    roles: ROLE_DEFAULT
    user:
      name: sys_admin
      password: wisdom@123

security:
  basic:
    enabled: false
  user:
    name: actuator
    password: 121212

application:
  security:
    authentication:
      jwt:
        secret: 0550224055e1848081dba46d8ad325f503fa141b
        # Token is valid 24 hours
        tokenValidityInSeconds: 86400
  swagger:
    title: API
    description: API documentation
    version: 0.0.1
    termsOfServiceUrl:
    contactName:
    contactUrl:
    contactEmail:
    license:
    licenseUrl:
  glusterfs:
    accessSubPath: v1/AUTH_zvolume
    accessKeyID: zvolume
    secretKey:
    bucketName: bucket1
    endpoint: http://192.168.102.61:8080
  wbcode:
    openWbCode: true
  netty:
    lineClientHost: 10.180.245.169
    lineClientPort: 9234
    elevatorClientHost: 10.180.245.169
    elevatorClientPort: 9234
    nettyServerHost: 10.180.245.169
    nettyServerPort: 9234
  MesParam:
    arriveSrcWbUrl: /api/wisdom/agvHandlingTask/arriveSrcWb
    leaveSrcWbUrl: /api/wisdom/agvHandlingTask/leaveSrcWb
    arriveDestWbWaitPortUrl: /api/wisdom/agvHandlingTask/arriveDestWbWaitPort
    arriveDestWbUrl: /api/wisdom/agvHandlingTask/arriveDestWb
    agvHandlingTaskUrl: /api/wisdom/agvHandlingTask
  hikParam:
    returnPodUrl: http://192.168.102.100/rcs/services/rest/hikTpsService/returnPod
    getOutPodUrl: http://192.168.102.100/rcs/services/rest/hikTpsService/getOutPod
    endTaskUrl: http://192.168.102.100/rcs/services/rest/hikTpsService/endAllTasksByTps
    rotatePodUrl: http://192.168.102.100/rcs/services/rest/hikTpsService/rotatePodByTps
    movePodUrl: http://192.168.102.100/rcs/services/rest/hikTpsService/genMoveTaskByPod
    genAgvSchedulingTaskUrl: http://192.168.102.100/rcs/services/rest/hikRpcService/genAgvSchedulingTask
    continueTaskUrl: http://10.180.245.169/rcs/services/rest/hikRpcService/continueTask
    cancelTaskUrl: http://192.168.102.100/rcs/services/rest/hikRpcService/cancelTask
    freeRobotUrl: http://10.180.245.169/rcs/services/rest/hikRpcService/freeRobot
    returnMapOrPodUrl: http://10.180.245.169/rcs/services/rest/hikRpcService/queryPodBerthAndMat
    returnTaskStatus:  http://10.180.245.169/rcs/services/rest/hikRpcService/queryTaskStatus
    finiTask:  http://10.180.245.169/rcs/services/rest/hikLiftService/finiTask
    tokenCode: e508bef3a47df47629ffb483058868da
    clientCode: USINSPUR
  outstock:
    noticeOutstockProcess: true
    allowHandOutstockSupplyCall: true
    forceKeepOutstockProcess: true
  rabbitmq:
    host: 10.180.245.169
    port: 5672
    username: admin
    password: admin
    virtualHost: /
  warn:
    checkName: name1;name2


mybatis:
  type-handlers-package: org.apache.ibatis.type.LocalDateTypeHandler

socketIO:
  port: 9003
  host: 0.0.0.0
  isHttps: false
  storePassword: newsys
  keyStore: tomcat.keystore
  jwt:
    secret: 0550224055e1848081dba46d8ad325f503fa141b
    tokenValidityInSeconds: 86400
    tokenValidityInSecondsForRememberMe: 86400
